
# using fixed ip addresses
# to see all network use docker network ls
# to see config use docker network inspect kuwabia-docker-compose_kuwaiba-net
# note gateway is 172.30.0.1 
networks:
  kuwaiba-net:
    ipam:
      config:
        - subnet: 172.30.0.0/24

volumes:
  data-kuwaiba: {}

services:

  kuwaiba:
 #    image: ${DOCKER_REGISTRY:-docker.io}/neotropic/kuwaiba:${KUWAIBA_VERSION:-v2.1-nightly}
    image: onms-integration/kuwaiba
    build: ./container-fs/kuwaiba/
    container_name: kuwaiba
    hostname: kuwaiba
 #   environment:
 #    URL_DATA: https://sourceforge.net/projects/kuwaiba/files/Version%202.x/kuwaiba_server_2.1.1_stable.zip
    volumes:
      - data-kuwaiba:/data
      - ./container-fs/kuwaiba/start.sh:/start.sh
      - ./container-fs/kuwaiba/data-overlay:/data-overlay
      - ./container-fs/kuwaiba/data-zip:/data-zip
    ports:
      - "8080:8080"
      - "8081:8081"

    # To combine stderr and stdout into the stdout stream, we append this to a command: 2>&1
    # command: sh -c "java -jar /opt/programs/kuwaiba_server_2.1.1-stable.jar > /data/logs/kuwaiba_$(date +%Y%m%d_%H%M%S).log 2>&1"
    command: sh /start.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "-I", "http://localhost:8080/kuwaiba/"]
      interval: 30s
      timeout: 5s
      retries: 1
    networks:
      kuwaiba-net:
        ipv4_address: 172.30.0.55

  pris:
    container_name: pris
    image: ${DOCKER_REGISTRY:-docker.io}/${DOCKER_ORG:-opennms}/${MINION_OCI:-pris}:${PRIS_VERSION:-latest}
    environment:
      - TZ=Europe/Berlin
      - JAVA_OPTS=-XX:+PrintGCDetails -XX:+UnlockExperimentalVMOptions
    volumes:
      - ./container-fs/pris/requisitions:/opt/opennms-pris/requisitions
      - ./container-fs/pris/scriptsteps:/opt/opennms-pris/scriptsteps
      - ./container-fs/pris/lib/jackson-annotations-2.16.0.jar:/opt/opennms-pris/lib/jackson-annotations-2.16.0.jar
      - ./container-fs/pris/lib/jackson-core-2.16.0.jar:/opt/opennms-pris/lib/jackson-core-2.16.0.jar
      - ./container-fs/pris/lib/jackson-databind-2.16.0.jar:/opt/opennms-pris/lib/jackson-databind-2.16.0.jar
    healthcheck:
      test: ["CMD", "curl", "-f", "-I", "http://localhost:8000/pris/2.1.0/index.html"]
      interval: 30s
      timeout: 5s
      retries: 1
    ports:
      - "8000:8000"
    networks:
      kuwaiba-net:
        ipv4_address: 172.30.0.35
        